In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('MexicoCityBuildings.csv')

C:\Users\Apoorva\AppData\Local\Temp\ipykernel_22772\4002178220.py:1: DtypeWarning: Columns (1,3,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('MexicoCityBuildings.csv')

In [3]:
df['building'].value_counts()

yes                    113806
house                   40294
carport                 12766
terrace                  9364
apartments               8088
                        ...
TUMSA Santa Barbara         1
bakehouse                   1
bank                        1
basilica                    1
wayside_shrine              1
Name: building, Length: 89, dtype: int64

In [4]:
list(set(df['building']))

['garages',
 'stadium',
 'transportation',
 'retail',
 'boathouse',
 'Salon',
 'detached',
 'farm',
 'supermarket',
 'semidetached_house',
 'bungalow',
 'hospital',
 'kindergarten',
 'stable',
 'yes',
 'pavilion',
 'hut',
 'basilica',
 'grandstand',
 'religious_administration',
 'church',
 'university',
 'service',
 'wayside_shrine',
 'construction',
 'farm_auxiliary',
 'barn',
 'industrial',
 'cathedral',
 'civic',
 'shed',
 'storage_tank',
 'cowshed',
 'pillar',
 'hangar',
 'riding_hall',
 'warehouse',
 'bunker',
 'Modulo de policia',
 'garage',
 'house',
 'ruins',
 'government',
 'carport',
 'train_station',
 'fronton',
 'hotel',
 'manufacture',
 'convi',
 'Escuela',
 'Farmacia_y_Consultorios_Medicos',
 'TUMSA Santa Barbara',
 'INFRAESTRUCTURA',
 'pyramid',
 'apartments',
 'sports_hall',
 'bakehouse',
 'cabin',
 'tower',
 'bank',
 'store',
 'events_venue',
 'college',
 'temple',
 'sports_centre',
 'roof',
 'chapel',
 'public',
 'terrace',
 'checkpoint',
 'no',
 'market',
 'townhall',
 'school',
 'fuel',
 'auditorio',
 'taller',
 'parking',
 'commercial',
 'residential',
 'Salon_comunitario',
 'kiosk',
 'bridge',
 'local',
 'shrine',
 'stupa',
 'greenhouse',
 'abasto',
 'office']

In [5]:
df

,name,name:en,building,building:levels,building:materials,addr:full,addr:housenumber,addr:street,addr:city,office,...,ADM1ALT2ES,ADM0_ES,ADM0_PCODE,date,validOn,validTo,Shape_Leng,Shape_Area,lon,lat
0,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.959145,19.174023
1,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.958902,19.173881
2,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.958831,19.173856
3,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.957499,19.174133
4,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.957630,19.174264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209576,NaN,NaN,school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.653827,19.284764
209577,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.656001,19.283160
209578,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.047458,19.485236
209579,NaN,NaN,school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.057386,19.485507
209580,NaN,NaN,school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.056977,19.485496

In [6]:
#df['name'] = df.index.map(lambda i: f'SaoPau loBuilding{i}')

In [7]:
df.reset_index(inplace = True)

In [8]:
df['name']=df.apply(lambda x: 'mex'+str(x['index']), axis = 1)

In [9]:
df

,index,name,name:en,building,building:levels,building:materials,addr:full,addr:housenumber,addr:street,addr:city,...,ADM1ALT2ES,ADM0_ES,ADM0_PCODE,date,validOn,validTo,Shape_Leng,Shape_Area,lon,lat
0,0,mex0,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.959145,19.174023
1,1,mex1,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.958902,19.173881
2,2,mex2,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.958831,19.173856
3,3,mex3,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.957499,19.174133
4,4,mex4,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.957630,19.174264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209576,209576,mex209576,NaN,school,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.653827,19.284764
209577,209577,mex209577,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.656001,19.283160
209578,209578,mex209578,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.047458,19.485236
209579,209579,mex209579,NaN,school,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.057386,19.485507
209580,209580,mex209580,NaN,school,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.056977,19.485496

In [10]:
df['name'] = df.index.map(lambda i: f'MexicoCityBuilding{i}')

In [11]:
df

,index,name,name:en,building,building:levels,building:materials,addr:full,addr:housenumber,addr:street,addr:city,...,ADM1ALT2ES,ADM0_ES,ADM0_PCODE,date,validOn,validTo,Shape_Leng,Shape_Area,lon,lat
0,0,MexicoCityBuilding0,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.959145,19.174023
1,1,MexicoCityBuilding1,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.958902,19.173881
2,2,MexicoCityBuilding2,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.958831,19.173856
3,3,MexicoCityBuilding3,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.957499,19.174133
4,4,MexicoCityBuilding4,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.957630,19.174264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209576,209576,MexicoCityBuilding209576,NaN,school,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.653827,19.284764
209577,209577,MexicoCityBuilding209577,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.656001,19.283160
209578,209578,MexicoCityBuilding209578,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.047458,19.485236
209579,209579,MexicoCityBuilding209579,NaN,school,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.057386,19.485507
209580,209580,MexicoCityBuilding209580,NaN,school,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.056977,19.485496

In [12]:
house = ['yes', 'apartments', 'residential', 'house', 'dormitory', 'bungalow', 'semidetached_house']
school = ['school', 'university', 'kindergarten', 'college']
public_transport = ['train_station', 'transportation']
hospital = ['hospital']

In [13]:
df_building = df[df['building'].isin(house)]
df_school = df[df['building'].isin(school)]
df_pt = df[df['building'].isin(public_transport)]
df_hospital = df[df['building'].isin(hospital)]

In [14]:
toilet = ['toilets']
civic = ['civic']
public = ['public']
fire = ['fire_station']
sports = ['grandstand', 'pavilion', 'riding_hall', 'sports_hall', 'sports_centre', 'stadium']
govt = ['government']
supermarket = ['supermarket']

df_toilet = df[df['building'].isin(toilet)]
df_civic = df[df['building'].isin(civic)]
df_public = df[df['building'].isin(public)]
df_fire = df[df['building'].isin(fire)]
df_sports = df[df['building'].isin(sports)]
df_govt = df[df['building'].isin(govt)]
df_supermarket = df[df['building'].isin(supermarket)]

df_toilet.to_csv('Toilet.csv', index = False)
df_civic.to_csv('Civic.csv', index = False)
df_public.to_csv('Public.csv', index = False)
df_fire.to_csv('Fire.csv', index = False)
df_sports.to_csv('Sports.csv', index = False)
df_govt.to_csv('Government.csv', index = False)
df_supermarket.to_csv('Supermarket.csv', index = False)

In [15]:
df_building.to_csv('MexicoCityBuildingsFinal.csv', index = False)
df_school.to_csv('School.csv', index = False)
df_pt.to_csv('Transport.csv', index = False)
df_hospital.to_csv('Hospital.csv', index = False)

In [16]:
df_building

,index,name,name:en,building,building:levels,building:materials,addr:full,addr:housenumber,addr:street,addr:city,...,ADM1ALT2ES,ADM0_ES,ADM0_PCODE,date,validOn,validTo,Shape_Leng,Shape_Area,lon,lat
0,0,MexicoCityBuilding0,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.959145,19.174023
1,1,MexicoCityBuilding1,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.958902,19.173881
2,2,MexicoCityBuilding2,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.958831,19.173856
3,3,MexicoCityBuilding3,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.957499,19.174133
4,4,MexicoCityBuilding4,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.957630,19.174264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209572,209572,MexicoCityBuilding209572,NaN,yes,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.119749,19.683755
209573,209573,MexicoCityBuilding209573,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.869651,19.950939
209574,209574,MexicoCityBuilding209574,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.846846,19.947589
209577,209577,MexicoCityBuilding209577,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.656001,19.283160
209578,209578,MexicoCityBuilding209578,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.047458,19.485236

In [17]:
df_supermarket

,index,name,name:en,building,building:levels,building:materials,addr:full,addr:housenumber,addr:street,addr:city,...,ADM1ALT2ES,ADM0_ES,ADM0_PCODE,date,validOn,validTo,Shape_Leng,Shape_Area,lon,lat
47233,47233,MexicoCityBuilding47233,NaN,supermarket,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.553380,19.287756
57851,57851,MexicoCityBuilding57851,NaN,supermarket,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.665817,19.318962
67038,67038,MexicoCityBuilding67038,NaN,supermarket,1,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.276650,19.399513
99089,99089,MexicoCityBuilding99089,NaN,supermarket,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.202826,19.550995
166428,166428,MexicoCityBuilding166428,NaN,supermarket,NaN,NaN,NaN,222,Calle Vía José María Morelos,NaN,...,NaN,México,MX,2020/06/23,2021/06/18,NaN,13.430924,1.921861,-99.042014,19.570606