In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('KarachiBuildings.csv')

In [3]:
df['building'].value_counts()

yes               43507
house             33448
apartments         5252
bunglows            880
industrial          620
commercial          324
residential         322
university          193
construction        162
school              130
mosque              117
warehouse           103
hospital            101
no                   94
college              48
roof                 29
detached             23
ruins                22
hangar               19
hotel                13
stadium              13
farm_auxiliary        9
terrace               9
office                9
public                8
garage                7
bungalow              5
retail                5
greenhouse            4
bunker                4
service               3
dormitory             3
transportation        2
grandstand            2
mall                  2
sports_centre         2
civic                 2
shed                  2
church                2
parking               2
carport               1
tower No-1            1
government            1
yrs                   1
ballroom              1
Name: building, dtype: int64

In [4]:
df

,name,name_en,building,building_l,building_m,addr_full,addr_house,addr_stree,addr_city,office,...,ADM2ALT2EN,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,date,validOn,validTo,lon,lat
0,Allah Wali,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.976520,24.870707
1,Baghdadi,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.994912,24.860076
2,Qayyumi,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.992142,24.865603
3,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.998488,24.869432
4,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.998157,24.869155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85502,NaN,NaN,yes,3.0,NaN,NaN,NaN,PECHS Block 2,Karachi,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.058398,24.870653
85503,NaN,NaN,yes,3.0,NaN,NaN,NaN,PECHS Block 2,Karachi,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.058432,24.870773
85504,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.971928,24.834162
85505,Karachi Public School (Korangi Creek),NaN,yes,6.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.103170,24.817748
85506,People's Football Stadium,NaN,yes,NaN,NaN,NaN,NaN,"Mauripur Rd, Nayabad Liaquat Colony, Karachi, ...",Karachi,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.988293,24.858577

In [5]:
df['name'] = df.index.map(lambda i: f'KarachiBuilding{i}')

In [6]:
df

,name,name_en,building,building_l,building_m,addr_full,addr_house,addr_stree,addr_city,office,...,ADM2ALT2EN,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,date,validOn,validTo,lon,lat
0,KarachiBuilding0,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.976520,24.870707
1,KarachiBuilding1,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.994912,24.860076
2,KarachiBuilding2,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.992142,24.865603
3,KarachiBuilding3,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.998488,24.869432
4,KarachiBuilding4,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.998157,24.869155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85502,KarachiBuilding85502,NaN,yes,3.0,NaN,NaN,NaN,PECHS Block 2,Karachi,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.058398,24.870653
85503,KarachiBuilding85503,NaN,yes,3.0,NaN,NaN,NaN,PECHS Block 2,Karachi,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.058432,24.870773
85504,KarachiBuilding85504,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.971928,24.834162
85505,KarachiBuilding85505,NaN,yes,6.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.103170,24.817748
85506,KarachiBuilding85506,NaN,yes,NaN,NaN,NaN,NaN,"Mauripur Rd, Nayabad Liaquat Colony, Karachi, ...",Karachi,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.988293,24.858577

In [7]:
house = ['yes', 'apartments', 'residential', 'house', 'dormitory', 'bungalow', 'semidetached_house']
school = ['school', 'university', 'kindergarten', 'college']
public_transport = ['train_station', 'transportation']
hospital = ['hospital']

In [8]:
toilet = ['toilets']
civic = ['civic']
public = ['public']
fire = ['fire_station']
sports = ['grandstand', 'pavilion', 'riding_hall', 'sports_hall', 'sports_centre', 'stadium']
govt = ['government']
supermarket = ['supermarket']

df_toilet = df[df['building'].isin(toilet)]
df_civic = df[df['building'].isin(civic)]
df_public = df[df['building'].isin(public)]
df_fire = df[df['building'].isin(fire)]
df_sports = df[df['building'].isin(sports)]
df_govt = df[df['building'].isin(govt)]
df_supermarket = df[df['building'].isin(supermarket)]

df_toilet.to_csv('Toilet.csv', index = False)
df_civic.to_csv('Civic.csv', index = False)
df_public.to_csv('Public.csv', index = False)
df_fire.to_csv('Fire.csv', index = False)
df_sports.to_csv('Sports.csv', index = False)
df_govt.to_csv('Government.csv', index = False)
df_supermarket.to_csv('Supermarket.csv', index = False)

In [9]:
df_building = df[df['building'].isin(house)]
df_school = df[df['building'].isin(school)]
df_pt = df[df['building'].isin(public_transport)]
df_hospital = df[df['building'].isin(hospital)]

In [10]:
df_building.to_csv('KarachiBuildingsFinal.csv', index = False)
df_school.to_csv('School.csv', index = False)
df_pt.to_csv('Transport.csv', index = False)
df_hospital.to_csv('Hospital.csv', index = False)

In [11]:
df_sports

,name,name_en,building,building_l,building_m,addr_full,addr_house,addr_stree,addr_city,office,...,ADM2ALT2EN,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,date,validOn,validTo,lon,lat
539,KarachiBuilding539,NaN,grandstand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.247559,24.923412
4624,KarachiBuilding4624,NaN,sports_centre,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.054067,24.881922
5033,KarachiBuilding5033,NaN,stadium,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.053468,24.881526
5034,KarachiBuilding5034,NaN,stadium,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.053758,24.881351
41873,KarachiBuilding41873,NaN,stadium,NaN,NaN,NaN,NaN,Stadium Road,Karachi,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.081908,24.894989
57772,KarachiBuilding57772,NaN,sports_centre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.115530,24.933101
57783,KarachiBuilding57783,NaN,stadium,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.053654,24.881054
63411,KarachiBuilding63411,NaN,stadium,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.053357,24.881221
80613,KarachiBuilding80613,NaN,stadium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.008553,24.861312
80976,KarachiBuilding80976,NaN,grandstand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.148131,24.793432
83397,KarachiBuilding83397,NaN,stadium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.008521,24.861966
83398,KarachiBuilding83398,NaN,stadium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.009165,24.862003
83399,KarachiBuilding83399,NaN,stadium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.009496,24.861622
84556,KarachiBuilding84556,NaN,stadium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.991002,24.851065
84557,KarachiBuilding84557,NaN,stadium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,66.991869,24.850680
84565,KarachiBuilding84565,NaN,stadium,4.0,NaN,NaN,NaN,Stadium Road,Karachi,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.081215,24.896117
84566,KarachiBuilding84566,NaN,stadium,4.0,NaN,NaN,NaN,Stadium Road,Karachi,NaN,...,NaN,Sindh,PK7,Pakistan,PK,2022/09/02,2022/09/09,NaN,67.082338,24.895547