In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('ManilaBuildings.csv')

C:\Users\Apoorva\AppData\Local\Temp\ipykernel_14932\3160264591.py:1: DtypeWarning: Columns (1,3,5,6,9,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('ManilaBuildings.csv')

In [3]:
df['building'].value_counts()

yes                                         1013816
house                                        111321
residential                                    3892
school                                         3641
apartments                                     3255
                                             ...
clinic                                            1
Philippine_Nurses_Association                     1
Recreational_Building                             1
Marikina Clean Food and Water Laboratory          1
convent                                           1
Name: building, Length: 129, dtype: int64

In [4]:
list(set(df['building']))

['crypt',
 'government',
 'education',
 'chapel',
 'hut',
 'kiosk',
 'healthcare',
 'church',
 'greenhouse',
 'mausoleum',
 'historic',
 'hall',
 'destroyed',
 'government_office',
 'manufacture',
 'hotel',
 'kingdom_hall',
 'fire_station',
 'tent',
 'market',
 'Rualo Apartment',
 'yes',
 'monastery',
 'accommodation',
 'dormitory',
 'silo',
 'civic',
 'hospital',
 'ruins',
 'retain',
 'Marikina Clean Food and Water Laboratory',
 'water station',
 'water_tower',
 'no',
 'religious',
 'pop-up_store',
 'train_station',
 'gymnasium',
 'university',
 'proposed',
 'bar',
 'no_roof',
 'townhall',
 'Condominium',
 'bridge',
 'barn',
 'place_of_worship',
 'security_booth',
 'residential',
 'public',
 'clubhouse',
 'amenity',
 'supermarket',
 'institutional',
 'garages',
 'storage',
 'bulding',
 'logistics',
 'canopy',
 'shop',
 'container',
 'office',
 'commercial',
 'service',
 'multiple',
 'Bagumbayan Riverboat Station',
 'storage_tank',
 'medical',
 'gazeebo',
 'semidetached_house',
 'stadium',
 'parking',
 'mosque',
 'columbarium',
 'transformer_tower',
 'Recreational_Building',
 'Baicapture HQ',
 'mall',
 'grandstand',
 'sports_hall',
 'terrace',
 'brgy_hall',
 'condominium',
 'toilets',
 'hangar',
 'convent',
 'transportation',
 'stilt_house',
 'bakehouse',
 'cathedral',
 'garage',
 'shed',
 'wall',
 'marquee',
 'carport',
 'synagogue',
 'sports_centre',
 'booth',
 'retail',
 'multipurpose',
 'military',
 'museum',
 'warehouse',
 'pharmacy',
 'industrial',
 'construction',
 'kindergarten',
 'bank',
 'tower',
 'Subdivision_Administration_Office',
 'part',
 'gatehouse',
 'school',
 'restaurant',
 'factory',
 'Philippine_Nurses_Association',
 'abandoned',
 'house',
 'bakery',
 'apartments',
 'roof',
 'Chicken inasal',
 'temple',
 'guardhouse',
 'detached',
 'clinic',
 'pavilion',
 'collapsed',
 'college']

In [5]:
df

,name,name:en,building,building:levels,building:materials,addr:full,addr:housenumber,addr:street,addr:city,office,...,ADM0_PCODE,date,validOn,validTo,Shape_Leng,Shape_Area,ADM2ALT1EN,AREA_SQKM,lon,lat
0,NaN,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.054572,14.602854
1,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.054084,14.602082
2,NaN,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.054458,14.602308
3,NaN,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.053739,14.602178
4,NaN,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.053136,14.603513
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1151104,Petron,NaN,roof,NaN,NaN,NaN,NaN,E. Rodriguez Jr. Avenue,Pasig,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.073146,14.576243
1151105,NaN,NaN,industrial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.087355,14.587389
1151106,Institute of Biology,NaN,yes,3,NaN,NaN,NaN,Ma. Regidor,Quezon City,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.070807,14.650831
1151107,NaN,NaN,school,NaN,NaN,NaN,NaN,NaN,Marikina,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.117397,14.652117
1151108,Philippine National Police Headquarters,NaN,office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.053218,14.609299

In [6]:
df['name'] = df.index.map(lambda i: f'ManilaBuilding{i}')

In [7]:
df

,name,name:en,building,building:levels,building:materials,addr:full,addr:housenumber,addr:street,addr:city,office,...,ADM0_PCODE,date,validOn,validTo,Shape_Leng,Shape_Area,ADM2ALT1EN,AREA_SQKM,lon,lat
0,ManilaBuilding0,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.054572,14.602854
1,ManilaBuilding1,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.054084,14.602082
2,ManilaBuilding2,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.054458,14.602308
3,ManilaBuilding3,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.053739,14.602178
4,ManilaBuilding4,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.053136,14.603513
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1151104,ManilaBuilding1151104,NaN,roof,NaN,NaN,NaN,NaN,E. Rodriguez Jr. Avenue,Pasig,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.073146,14.576243
1151105,ManilaBuilding1151105,NaN,industrial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.087355,14.587389
1151106,ManilaBuilding1151106,NaN,yes,3,NaN,NaN,NaN,Ma. Regidor,Quezon City,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.070807,14.650831
1151107,ManilaBuilding1151107,NaN,school,NaN,NaN,NaN,NaN,NaN,Marikina,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.117397,14.652117
1151108,ManilaBuilding1151108,NaN,office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.053218,14.609299

In [8]:
house = ['yes', 'apartments', 'residential', 'house', 'dormitory', 'bungalow', 'semidetached_house']
school = ['school', 'university', 'kindergarten', 'college', 'education', 'institutional']
public_transport = ['train_station', 'transportation']
hospital = ['hospital', 'clinic']

In [9]:
df_building = df[df['building'].isin(house)]
df_school = df[df['building'].isin(school)]
df_pt = df[df['building'].isin(public_transport)]
df_hospital = df[df['building'].isin(hospital)]

In [10]:
toilet = ['toilets']
civic = ['civic']
public = ['public']
fire = ['fire_station']
sports = ['grandstand', 'pavilion', 'riding_hall', 'sports_hall', 'sports_centre', 'stadium']
govt = ['government']
supermarket = ['supermarket']

df_toilet = df[df['building'].isin(toilet)]
df_civic = df[df['building'].isin(civic)]
df_public = df[df['building'].isin(public)]
df_fire = df[df['building'].isin(fire)]
df_sports = df[df['building'].isin(sports)]
df_govt = df[df['building'].isin(govt)]
df_supermarket = df[df['building'].isin(supermarket)]

df_toilet.to_csv('Toilet.csv', index = False)
df_civic.to_csv('Civic.csv', index = False)
df_public.to_csv('Public.csv', index = False)
df_fire.to_csv('Fire.csv', index = False)
df_sports.to_csv('Sports.csv', index = False)
df_govt.to_csv('Government.csv', index = False)
df_supermarket.to_csv('Supermarket.csv', index = False)

In [11]:
df_building

,name,name:en,building,building:levels,building:materials,addr:full,addr:housenumber,addr:street,addr:city,office,...,ADM0_PCODE,date,validOn,validTo,Shape_Leng,Shape_Area,ADM2ALT1EN,AREA_SQKM,lon,lat
0,ManilaBuilding0,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.054572,14.602854
1,ManilaBuilding1,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.054084,14.602082
2,ManilaBuilding2,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.054458,14.602308
3,ManilaBuilding3,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.053739,14.602178
4,ManilaBuilding4,NaN,house,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.053136,14.603513
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1151100,ManilaBuilding1151100,NaN,yes,NaN,NaN,NaN,NaN,Ortigas Avenue Extension,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.088695,14.589997
1151101,ManilaBuilding1151101,NaN,yes,7,NaN,NaN,NaN,Reina Regente,Manila,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.600152,0.003520,NaN,41.960090,120.973467,14.603101
1151102,ManilaBuilding1151102,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.063058,14.741103
1151103,ManilaBuilding1151103,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.038593,14.642583
1151106,ManilaBuilding1151106,NaN,yes,3,NaN,NaN,NaN,Ma. Regidor,Quezon City,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.070807,14.650831

In [12]:
df_building.to_csv('ManilaBuildingsFinal.csv', index = False)
df_school.to_csv('School.csv', index = False)
df_pt.to_csv('Transport.csv', index = False)
df_hospital.to_csv('Hospital.csv', index = False)

In [13]:
df_toilet

,name,name:en,building,building:levels,building:materials,addr:full,addr:housenumber,addr:street,addr:city,office,...,ADM0_PCODE,date,validOn,validTo,Shape_Leng,Shape_Area,ADM2ALT1EN,AREA_SQKM,lon,lat
207791,ManilaBuilding207791,NaN,toilets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.118916,14.659886
222653,ManilaBuilding222653,NaN,toilets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.109956,14.640990
667218,ManilaBuilding667218,NaN,toilets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.049468,14.653109
864687,ManilaBuilding864687,NaN,toilets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.949302,0.010582,NaN,126.090073,120.985945,14.718889
1119715,ManilaBuilding1119715,NaN,toilets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.948285,0.019613,NaN,233.767125,121.053864,14.577733
1123864,ManilaBuilding1123864,NaN,toilets,1,NaN,NaN,NaN,NaN,NaN,NaN,...,PH,2022/11/09,2023/11/06,NaN,0.933806,0.016492,NaN,196.722285,121.056189,14.564163