In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('SaoPauloBuildings.csv')

C:\Users\Apoorva\AppData\Local\Temp\ipykernel_21884\3714479509.py:1: DtypeWarning: Columns (1,3,5,6,7,8,9,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('SaoPauloBuildings.csv')

In [3]:
df['building'].value_counts()

yes               2335404
house              172643
apartments          12315
roof                 8686
residential          7179
                   ...
monument                1
swimming_pool           1
yes;commercial          1
roofg                   1
hospital;hotel          1
Name: building, Length: 199, dtype: int64

In [4]:
df

,name,name_en,building,building_l,building_m,addr_full,addr_house,addr_stree,addr_city,office,...,name_pt,osm_id,osm_type,lon,lat,shapeName,shapeISO,shapeID,shapeGroup,shapeType
0,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,381954819,ways_poly,-46.656189,-23.547673,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
1,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,381954829,ways_poly,-46.656407,-23.548160,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2,NaN,NaN,industrial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,243547095,ways_poly,-46.389406,-23.702792,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
3,NaN,NaN,farm,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,787791587,ways_poly,-47.842960,-22.989891,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
4,NaN,NaN,farm_auxiliary,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,896039126,ways_poly,-47.843091,-22.989530,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2581536,Banco do Brasil,NaN,yes,NaN,NaN,NaN,1995;2005,Avenida Adolfo Pinheiro,São Paulo,NaN,...,NaN,14687989,relations,-46.695310,-23.636889,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2581537,Hotel Ponte Aerea,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,18007942,relations,-46.662922,-23.623880,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2581538,Subestação Ponta Porã,NaN,industrial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7525587,relations,-46.717760,-23.546435,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2581539,NaN,NaN,roof,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6052882,relations,-47.398151,-22.565259,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2581540,Conservatório Villa Lobos,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,17995669,relations,-46.791714,-23.538123,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1

In [5]:
df['name'] = df.index.map(lambda i: f'SaoPauloBuilding{i}')

In [6]:
df

,name,name_en,building,building_l,building_m,addr_full,addr_house,addr_stree,addr_city,office,...,name_pt,osm_id,osm_type,lon,lat,shapeName,shapeISO,shapeID,shapeGroup,shapeType
0,SaoPauloBuilding0,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,381954819,ways_poly,-46.656189,-23.547673,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
1,SaoPauloBuilding1,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,381954829,ways_poly,-46.656407,-23.548160,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2,SaoPauloBuilding2,NaN,industrial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,243547095,ways_poly,-46.389406,-23.702792,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
3,SaoPauloBuilding3,NaN,farm,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,787791587,ways_poly,-47.842960,-22.989891,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
4,SaoPauloBuilding4,NaN,farm_auxiliary,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,896039126,ways_poly,-47.843091,-22.989530,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2581536,SaoPauloBuilding2581536,NaN,yes,NaN,NaN,NaN,1995;2005,Avenida Adolfo Pinheiro,São Paulo,NaN,...,NaN,14687989,relations,-46.695310,-23.636889,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2581537,SaoPauloBuilding2581537,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,18007942,relations,-46.662922,-23.623880,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2581538,SaoPauloBuilding2581538,NaN,industrial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7525587,relations,-46.717760,-23.546435,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2581539,SaoPauloBuilding2581539,NaN,roof,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6052882,relations,-47.398151,-22.565259,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2581540,SaoPauloBuilding2581540,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,17995669,relations,-46.791714,-23.538123,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1

In [7]:
house = ['apartments', 'residential', 'house', 'dormitory', 'bungalow', 'semidetached_house']
school = ['school', 'university', 'kindergarten', 'college']
public_transport = ['train_station', 'transportation']
hospital = ['hospital']

In [8]:
df_building = df[df['building'].isin(house)]
df_school = df[df['building'].isin(school)]
df_pt = df[df['building'].isin(public_transport)]
df_hospital = df[df['building'].isin(hospital)]

In [9]:
toilet = ['toilets']
civic = ['civic']
public = ['public']
fire = ['fire_station']
sports = ['grandstand', 'pavilion', 'riding_hall', 'sports_hall', 'sports_centre', 'stadium']
govt = ['government']
supermarket = ['supermarket']

df_toilet = df[df['building'].isin(toilet)]
df_civic = df[df['building'].isin(civic)]
df_public = df[df['building'].isin(public)]
df_fire = df[df['building'].isin(fire)]
df_sports = df[df['building'].isin(sports)]
df_govt = df[df['building'].isin(govt)]
df_supermarket = df[df['building'].isin(supermarket)]

df_toilet.to_csv('Toilet.csv', index = False)
df_civic.to_csv('Civic.csv', index = False)
df_public.to_csv('Public.csv', index = False)
df_fire.to_csv('Fire.csv', index = False)
df_sports.to_csv('Sports.csv', index = False)
df_govt.to_csv('Government.csv', index = False)
df_supermarket.to_csv('Supermarket.csv', index = False)

In [10]:
df_building.to_csv('SaoPauloBuildingsFinal.csv', index = False)
df_school.to_csv('School.csv', index = False)
df_pt.to_csv('Transport.csv', index = False)
df_hospital.to_csv('Hospital.csv', index = False)

In [12]:
df_public

,name,name_en,building,building_l,building_m,addr_full,addr_house,addr_stree,addr_city,office,...,name_pt,osm_id,osm_type,lon,lat,shapeName,shapeISO,shapeID,shapeGroup,shapeType
823,SaoPauloBuilding823,NaN,public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,813532910,ways_poly,-46.614849,-23.684227,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
3425,SaoPauloBuilding3425,NaN,public,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1206406683,ways_poly,-46.550935,-23.665401,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
4495,SaoPauloBuilding4495,NaN,public,2.0,NaN,NaN,NaN,Estrada Velocino de Araujo Bastos,NaN,NaN,...,NaN,684693369,ways_poly,-46.939262,-23.480199,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
5762,SaoPauloBuilding5762,NaN,public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1083023474,ways_poly,-46.451869,-23.664995,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
5767,SaoPauloBuilding5767,NaN,public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,991607806,ways_poly,-46.464789,-23.669647,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580475,SaoPauloBuilding2580475,NaN,public,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,17978268,relations,-46.535118,-23.657162,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2580514,SaoPauloBuilding2580514,NaN,public,3,NaN,NaN,95,Largo São Francisco,NaN,NaN,...,NaN,6321608,relations,-46.636958,-23.550134,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2580798,SaoPauloBuilding2580798,NaN,public,1,NaN,NaN,423,Avenida Fforde,Santo André,NaN,...,NaN,9715297,relations,-46.299142,-23.776061,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2580815,SaoPauloBuilding2580815,NaN,public,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6855690,relations,-46.624693,-23.528811,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1
2581208,SaoPauloBuilding2581208,NaN,public,NaN,NaN,NaN,118,Rua Capitão Neco,Cruzeiro,NaN,...,NaN,9225361,relations,-44.958275,-22.575651,Sao Paulo,BR-SP,14911670B46470234103867,BRA,ADM1